//跨域代理前缀
const API_PROXY_PREFIX = '/api'
const BASE_URL = process.env.NODE_ENV === 'production' ? process.env.VUE_APP_API_BASE_URL : API_PROXY_PREFIX
// const BASE_URL = process.env.VUE_APP_API_BASE_URL

module.exports = {
  LOGIN: `${BASE_URL}/user/login`,
  LOGOUT: `${BASE_URL}/user/delete`,
  REGISTER: `${BASE_URL}/user/register`,
  COMMON_RESERVATION: `${BASE_URL}/reserve/reserved_meeting`,
  ROOM_RESERVATION: `${BASE_URL}/reserve/room_reservation`,
  ROOM_RESERVATION_LIST:`${BASE_URL}/reserve/room_reservation_list`,
  AVALIABLE_ROOM: `${BASE_URL}/room/available_room_list`,
  SEARCH_USER: `${BASE_URL}/user/search`,
  SEARCH_EMPLOYEE: `${BASE_URL}/company/find_information`,
  INSTANT: `${BASE_URL}/reserve/instant_meeting`,
  GET_MEETINGSTATE: `${BASE_URL}/reserve/get_meetingstatus`,
  CONFIRM_MEETINGPASSWORD: `${BASE_URL}/reserve/confirm_meetingpassword`,
  CONFIRM_ROOM_RESERVATION:`${BASE_URL}/reserve/confirm_room_reservation`,
  ADD_MEETING: `${BASE_URL}/reserve/add_meeting`,
  CREATE_COMPANY: `${BASE_URL}/company/register`,
  FETCH_PERSON: `${BASE_URL}/company/employee_list`,
  FETCH_EMPLOYEE: `${BASE_URL}/company/get_common_employee`,
  FETCH_ADMIN: `${BASE_URL}/company/get_admin`,
  SET_ADMIN: `${BASE_URL}/company/set_admin`,
  DELETE_ADMIN: `${BASE_URL}/company/remove_admin`,
  SEARCH_INFORMATION: `${BASE_URL}/company/find_information`,
  SEARCH_COMPANY: `${BASE_URL}/company/search`,
  SEARCH_PERSON: `${BASE_URL}/user/search`,
  SEARCH_COMPANY_INFORMATION: `${BASE_URL}/company/information`,
  INVITE_PERSON: `${BASE_URL}/company/invitation`,
  APPLICATION_PERSON: `${BASE_URL}/user/application`,
  USER_NOTICE: `${BASE_URL}/user/notice_list`,
  DEAL_INVITATION: `${BASE_URL}/user/deal_invitation`,
  COMPANY_NOTICE: `${BASE_URL}/company/notice_list`,
  DEAL_APPLICATION: `${BASE_URL}/company/deal_application`,
  DEAL_READ: `${BASE_URL}/user/deal_read_only`,
  MODIFY_USER: `${BASE_URL}/user/modify`,
  USER_PASSWORD: `${BASE_URL}/user/password`,
  DISMISS_COMPANY: `${BASE_URL}/company/delete`,
  EDIT_ADDRESS:`${BASE_URL}/company/modify`,
  // CONFIRM_MEETINGPASSWORD:`${BASE_URL}/confirm_meetingpassword`,
  QUIT_COMPANY: `${BASE_URL}/user/quit`,
  DELETE_USER: `${BASE_URL}/user/delete`,
  FIRE_PERSON: `${BASE_URL}/company/fire`,
  ROOM_LIST: `${BASE_URL}/room/all_room_list`,
  CREATE_ROOM: `${BASE_URL}/room/setup`,
  DELETE_ROOM: `${BASE_URL}/room/delete`,
  CHANGE_ROOM: `${BASE_URL}/room/change_room_active`,
  EDIT_ROOM: `${BASE_URL}/room/modify`,
  UNREAD_NOTICE: `${BASE_URL}/user/notice_sum`,
  DEPARTMENT_LIST: `${BASE_URL}//department/list`,
  UPDATE_DEPARTMENT: `${BASE_URL}/user/join_department`,
  FIND_EMPLOYEE: `${BASE_URL}/department/find_employee`,
  DELETE_DEPARTMENT: `${BASE_URL}/department/delete`,
  CREATE_DEPARTMENT: `${BASE_URL}/department/setup`,
  EDIT_DEPARMENT: `${BASE_URL}/department/modify`,
  HISTORY: `${BASE_URL}/historical_meeting_list`,
  MY: `${BASE_URL}/my_meeting_list`,
  MEETING_RESULT: `${BASE_URL}/meeting_record`,
  
}
